"""add documents and prospects

Revision ID: 39c109150b33
Revises: f69e61acedc1
Create Date: 2026-07-08 16:00:03.474895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '39c109150b33'
down_revision: Union[str, None] = 'f69e61acedc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('youtube', 'upload', name='documentsource'), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='documentstatus'), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prospects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('keyword_search', name='prospectsource'), nullable=True),
    sa.Column('status', sa.Enum('pending_review', 'approved', 'rejected', name='prospectstatus'), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('uq_watch_creator_client_profile', 'watch_creators', ['client_id', 'profile_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_watch_creator_client_profile', 'watch_creators', type_='unique')
    op.drop_table('prospects')
    op.drop_table('client_documents')
    # ### end Alembic commands ###
