"""add client linkedin_url

Revision ID: beb4d174daa8
Revises: 39c109150b33
Create Date: 2026-07-09 06:37:36.364279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'beb4d174daa8'
down_revision: Union[str, None] = '39c109150b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('linkedin_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'linkedin_url')
    # ### end Alembic commands ###
