"""baseline

Revision ID: f69e61acedc1
Revises: 
Create Date: 2026-07-08 15:58:29.467140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f69e61acedc1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
